### ISSUE TITLE
Non tree graphs

### ISSUE THREAD

**Issue by Issam28** [DataManagementLab/deepdb-public#12]
Hi there,

Thank you for the code, I am wondering if this can be used in non-tree schemas such as JOB (full IMDB) ?

Thanks,

**Comment by ghost** [comment]
Hi, 

here, we have to distinguish between cyclic queries and cyclic schema graphs (not every query on a cyclic schema must be cyclic). What matters is whether the query is acyclic: since as long as the query graph is acyclic, the methods proposed in the paper would still work. For cyclic queries, one idea would be to compute the result for an acyclic subgraph and introduce additional join conditions in the filter predicates for DeepDB to account for the remaining edges in the join graph. 

With that being said, this particular implementation of DeepDB assumes that the schema is acyclic in the learning procedure. So here, you would have to adapt the code to support the full schema.

**Comment by Issam28** [comment]
Hi,
